---
name: tests

on:
  workflow_call:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      CB_ADDRESS: couchbase
      CB_CLIENT_PORT: 8091
      CB_NODE_PORT: 11210
      CB_PASSWORD: 123456
      CB_USERNAME: Administrator
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.26.4"
      - name: Couchbase Initialization
        run: |
          make cbinit
      - name: Couchbase Unit Tests
        run: |
          make test
      - name: Couchbase Acceptance Tests
        run: |
          make test
          make testacc
    services:
      couchbase:
        image: couchbase@sha256:5e505d8b98ebb827c4223d109ab93a71cbe1f2d947906b56a6e8f95c6d07a0f6
        ports:
          - 8091-8094:8091-8094
          - 11210:11210
          - 18091-18096:18091-18096
